# Generated by Django 3.1.1 on 2020-09-22 18:39

from django.db import migrations, models
import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200921_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 45 characters or fewer. Letters, digits and -/_ only.', max_length=45, unique=True, validators=[apps.users.validators.UsernameRegexValidator()]),
        ),
    ]
